'use client';

import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
  ReferenceLine,
} from 'recharts';
import ChartWatermark from '@/components/ChartWatermark';

// Generated by scripts/generate_amt_chart_data.py — do not edit manually
import generatedData from './data.json';
const data = generatedData as { income: number; bracket: number; actual: number }[];

const TEAL = '#319795';
const GRAY = '#718096';

function formatIncome(value: number) {
  if (value >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
  if (value >= 1000) return `$${(value / 1000).toFixed(0)}k`;
  return `$${value}`;
}

function CustomTooltip({
  active,
  payload,
  label,
}: {
  active?: boolean;
  payload?: { name: string; value: number; color?: string }[];
  label?: number;
}) {
  if (!active || !payload?.length || label === undefined) return null;
  const bracket = payload.find((p) => p.name === 'Tax savings (no AMT)')?.value ?? 0;
  const actual = payload.find((p) => p.name === 'Tax savings (with AMT)')?.value ?? 0;
  const clawback = bracket - actual;
  return (
    <div
      style={{
        background: '#fff',
        border: '1px solid #E2E8F0',
        borderRadius: 4,
        padding: '8px 12px',
        fontFamily: 'Inter, sans-serif',
        fontSize: 12,
      }}
    >
      <p style={{ margin: '0 0 4px', fontWeight: 600, color: '#1A202C' }}>
        Income: {formatIncome(label)}
      </p>
      <p style={{ margin: 0, color: TEAL }}>
        Without AMT: {bracket >= 0 ? '$' : '−$'}{Math.abs(bracket).toLocaleString()}
      </p>
      <p style={{ margin: 0, color: GRAY }}>
        With AMT: {actual >= 0 ? '$' : '−$'}{Math.abs(actual).toLocaleString()}
      </p>
      {clawback > 0 && (
        <p style={{ margin: 0, color: '#E53E3E' }}>
          AMT clawback: ${clawback.toLocaleString()}
        </p>
      )}
    </div>
  );
}

export default function AmtChartPage() {
  return (
    <div
      style={{
        width: '100%',
        maxWidth: 900,
        margin: '0 auto',
        padding: '16px 24px',
        fontFamily: 'Inter, sans-serif',
      }}
    >
      <ResponsiveContainer width="100%" height={420}>
          <AreaChart data={data} margin={{ top: 10, right: 20, bottom: 30, left: 60 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" />
            <XAxis
              dataKey="income"
              type="number"
              domain={[0, 'dataMax']}
              tickFormatter={formatIncome}
              tick={{ fontFamily: 'Inter, sans-serif', fontSize: 12 }}
              ticks={[0, 200000, 400000, 600000, 800000, 1000000]}
              label={{
                value: 'Household income',
                position: 'insideBottom',
                offset: -20,
                style: { fontFamily: 'Inter, sans-serif', fontSize: 13 },
              }}
            />
            <YAxis
              tickFormatter={(v: number) => {
                const abs = Math.abs(v);
                const label = abs >= 1000 ? `$${(abs / 1000).toFixed(0)}k` : `$${abs}`;
                return v < 0 ? `−${label}` : label;
              }}
              tick={{ fontFamily: 'Inter, sans-serif', fontSize: 12 }}
              label={{
                value: 'Tax savings (negative = tax increase)',
                angle: -90,
                position: 'insideLeft',
                offset: -45,
                style: { fontFamily: 'Inter, sans-serif', fontSize: 13 },
              }}
            />
            <ReferenceLine y={0} stroke="#A0AEC0" strokeDasharray="3 3" />
            <Tooltip content={<CustomTooltip />} />
            <Legend
              verticalAlign="top"
              wrapperStyle={{ fontFamily: 'Inter, sans-serif', fontSize: 12 }}
            />
            <Area
              type="linear"
              dataKey="bracket"
              name="Tax savings (no AMT)"
              stroke={TEAL}
              fill={TEAL}
              fillOpacity={0.15}
              strokeWidth={2}
            />
            <Area
              type="linear"
              dataKey="actual"
              name="Tax savings (with AMT)"
              stroke={GRAY}
              fill={GRAY}
              fillOpacity={0.15}
              strokeWidth={2}
            />
          </AreaChart>
        </ResponsiveContainer>
      <ChartWatermark />
    </div>
  );
}
